services:
  db:
    image: surrealdb/surrealdb:latest
    restart: always
    container_name: triple-A-db
    ports:
      - "8000:8000"
    command:
      - start
      - --log=trace
      - --user=root
      - --pass=root
      - file:///data
    volumes:
      - /home/omfi/tripleA-bot/db2/data:/data
      - /home/omfi/tripleA-bot/db2/logs:/logs
