version: '3.8'

services:
  triple-a-bot-db:
    container_name: triple-a-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<PASSWORD>
    ports:
      - 8001:5432
    volumes:
      - ./root:/var/lib/postgresql/data
