version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toxix123
    ports:
      - 8001:5432
    volumes:
      - /home/omfi/tripleA-bot/db/root:/var/lib/postgresql/data
